/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelgDinBilRouteImport } from './routes/selg-din-bil'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FinansieringRouteImport } from './routes/finansiering'
import { Route as BilutvalgRouteImport } from './routes/bilutvalg'
import { Route as IndexRouteImport } from './routes/index'

const SelgDinBilRoute = SelgDinBilRouteImport.update({
  id: '/selg-din-bil',
  path: '/selg-din-bil',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FinansieringRoute = FinansieringRouteImport.update({
  id: '/finansiering',
  path: '/finansiering',
  getParentRoute: () => rootRouteImport,
} as any)
const BilutvalgRoute = BilutvalgRouteImport.update({
  id: '/bilutvalg',
  path: '/bilutvalg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilutvalg': typeof BilutvalgRoute
  '/finansiering': typeof FinansieringRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg-din-bil': typeof SelgDinBilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilutvalg': typeof BilutvalgRoute
  '/finansiering': typeof FinansieringRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg-din-bil': typeof SelgDinBilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilutvalg': typeof BilutvalgRoute
  '/finansiering': typeof FinansieringRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/selg-din-bil': typeof SelgDinBilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilutvalg'
    | '/finansiering'
    | '/kontakt'
    | '/om-oss'
    | '/selg-din-bil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bilutvalg'
    | '/finansiering'
    | '/kontakt'
    | '/om-oss'
    | '/selg-din-bil'
  id:
    | '__root__'
    | '/'
    | '/bilutvalg'
    | '/finansiering'
    | '/kontakt'
    | '/om-oss'
    | '/selg-din-bil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilutvalgRoute: typeof BilutvalgRoute
  FinansieringRoute: typeof FinansieringRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  SelgDinBilRoute: typeof SelgDinBilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selg-din-bil': {
      id: '/selg-din-bil'
      path: '/selg-din-bil'
      fullPath: '/selg-din-bil'
      preLoaderRoute: typeof SelgDinBilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finansiering': {
      id: '/finansiering'
      path: '/finansiering'
      fullPath: '/finansiering'
      preLoaderRoute: typeof FinansieringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilutvalg': {
      id: '/bilutvalg'
      path: '/bilutvalg'
      fullPath: '/bilutvalg'
      preLoaderRoute: typeof BilutvalgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilutvalgRoute: BilutvalgRoute,
  FinansieringRoute: FinansieringRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  SelgDinBilRoute: SelgDinBilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
